# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IXcqZYtb9jXsmPJSfn9aDJwlvVPyAPfB
"""

import pandas as pd

df = pd.read_csv('sample_data/california_housing_train.csv')

df.head(n = 10)

df.tail(n = 2)

df.shape

df.isnull()

df.isnull().sum()

df.dtypes

df.columns

df[['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value']]

df[df['housing_median_age'] < 20]

df[df['housing_median_age'] < 20]['total_rooms']

df[(df['housing_median_age'] < 20) & (df['housing_median_age'] > 10)]['total_rooms']

df[(df['housing_median_age'] < 20) & (df['housing_median_age'] > 10)][['total_rooms', 'housing_median_age']]

print(df['population'].max())

print(df['population'].min())

print(df['population'].mean())

print(df['population'].sum())

print(df[['population', 'total_rooms']].median())

df.describe()

import seaborn as sns

sns.scatterplot(data=df, x='longitude', y='latitude')

sns.scatterplot(data=df, x='households', y='population', hue='total_rooms')

sns.scatterplot(data=df, x='households', y='population', hue='total_rooms', size=10)

cols = ['population', 'median_income', 'housing_median_age', 'median_house_value']
g = sns.PairGrid(df[cols])
g.map(sns.scatterplot)

sns.relplot(x='latitude', y='median_house_value', kind='line', data=df)

sns.relplot(x='longitude', y='median_house_value', kind='line', data=df)

sns.relplot(data=df, x='latitude', y='longitude', hue='median_house_value')

sns.histplot(data=df, x='median_income')

sns.histplot(data=df, x='housing_median_age')

sns.histplot(data=df[df['housing_median_age'] > 50], x = 'median_income')

df.loc[df['housing_median_age'] <= 20, 'housing_median_age']

df.columns

df.loc[df['housing_median_age'] <= 20, 'age_group'] = 'Молодые'
df.loc[(df['housing_median_age'] > 20) & (df['housing_median_age'] <= 50), 'age_group'] = 'Ср. возраст'
df.loc[df['housing_median_age'] > 50, 'age_group'] = 'Пожилые'

df.drop('age_groupe', axis=1, inplace=True)

df.columns

df.head()

df.groupby('age_group')['median_income'].mean().plot(kind='bar')

df.loc[df['median_income'] > 6, 'income_group'] = 'rich'
df.loc[df['median_income'] < 6, 'income_group'] = 'everyone_else'

df.head()

df.columns

sns.histplot(data = df, x = 'median_house_value', hue = 'income_group')